name = "device-preview"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.production]
name = "device-preview-production"

[build]
command = "npm run build"
cwd = "./"
main = "./dist/index.js"

[build.upload]
format = "modules"
main = "./dist/index.js"